### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by steom** [MGMCN/P2P-File-Sharing#18]
these commands is outdated

$ go get -t github.com/libp2p/go-libp2p@v0.28.2
$ go get -t github.com/chzyer/readline
$ go mod tidy
$ go build -o p2pnode ./main

now what is the correct and working command line?

$ go install github.com/libp2p/go-libp2p@latest
$
$
$

**Comment by MGMCN** [comment]
try this 👇🏻
```bash
$ go get -u github.com/libp2p/go-libp2p@latest
$ go get -t github.com/chzyer/readline
$ go mod tidy
$ go build -o p2pnode ./main
```

**Comment by steom** [comment]
i need to first run
$ go mod init randomname

$ go get -u github.com/libp2p/go-libp2p@latest  OK
$ go get -t github.com/chzyer/readline OK
$ go mod tidy [error](go: warning: "all" matched no packages)

using $ go install github.com/MGMCN/P2P-File-Sharing@latest

would make things a lot easier, if that were possible

**Comment by MGMCN** [comment]
```bash
$ git clone https://github.com/MGMCN/P2P-File-Sharing.git
$ cd P2P-File-Sharing
$ go get -u github.com/libp2p/go-libp2p@latest
$ go get -t github.com/chzyer/readline
$ go mod tidy
$ go build -o p2pnode ./main
```

**Comment by MGMCN** [comment]
![WeChatf4eadebce6c4494eea0eddcc4db02f7c](https://github.com/MGMCN/P2P-File-Sharing/assets/49364055/4111d1ff-55f4-4142-ab81-d3133ff21888)

Maybe you missed some details. It's build in my project folder. （A golang version of go 1.20 would be better.）
